name: Deploy to SquareCloud

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn
        
      - name: Zip project
        run: |
          zip -r app.zip * -x .github/* node_modules/*

      - name: Deploy to SquareCloud
        run: |
          # Coloque aqui os comandos necessários para implantar no SquareCloud
          curl --location 'https://api.squarecloud.app/v2/apps/${{ SQUARE_CLOUD_APP_ID }}/commit?restart=boolean' \
          --header 'Authorization: ${{ SQUARE_CLOUD_API_KEY }}' \
          --form 'file=@"./app.zip"'
